## Imports

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

## Get the data from the file epi_r.csv

In [2]:
df = pd.read_csv('data/epi_r.csv')
df.head()

,title,rating,calories,protein,fat,sodium,#cakeweek,#wasteless,22-minute meals,3-ingredient recipes,...,yellow squash,yogurt,yonkers,yuca,zucchini,cookbooks,leftovers,snack,snack week,turkey
0,"Lentil, Apple, and Turkey Wrap",2.500,426.0,30.0,7.0,559.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Boudin Blanc Terrine with Red Onion Confit,4.375,403.0,18.0,23.0,1439.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Potato and Fennel Soup Hodge,3.750,165.0,6.0,7.0,165.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Mahi-Mahi in Tomato Olive Sauce,5.000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Spinach Noodle Casserole,3.125,547.0,20.0,32.0,452.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## info(), describe() and count() methods in order to understand DataFrame better

In [3]:
for i in df.columns:
    print(i)

title
rating
calories
protein
fat
sodium
#cakeweek
#wasteless
22-minute meals
3-ingredient recipes
30 days of groceries
advance prep required
alabama
alaska
alcoholic
almond
amaretto
anchovy
anise
anniversary
anthony bourdain
aperitif
appetizer
apple
apple juice
apricot
arizona
artichoke
arugula
asian pear
asparagus
aspen
atlanta
australia
avocado
back to school
backyard bbq
bacon
bake
banana
barley
basil
bass
bastille day
bean
beef
beef rib
beef shank
beef tenderloin
beer
beet
bell pepper
berry
beverly hills
birthday
biscuit
bitters
blackberry
blender
blue cheese
blueberry
boil
bok choy
bon appétit
bon app��tit
boston
bourbon
braise
bran
brandy
bread
breadcrumbs
breakfast
brie
brine
brisket
broccoli
broccoli rabe
broil
brooklyn
brown rice
brownie
brunch
brussel sprout
buffalo
buffet
bulgaria
bulgur
burrito
butter
buttermilk
butternut squash
butterscotch/caramel
cabbage
cake
california
calvados
cambridge
campari
camping
canada
candy
candy thermometer
cantaloupe
capers
caraway
cardamom
carrot
cashew
casserole/gratin
cauliflower
caviar
celery
chambord
champagne
chard
chartreuse
cheddar
cheese
cherry
chestnut
chicago
chicken
chickpea
chile
chile pepper
chili
chill
chive
chocolate
christmas
christmas eve
cilantro
cinco de mayo
cinnamon
citrus
clam
clove
cobbler/crumble
cocktail
cocktail party
coconut
cod
coffee
coffee grinder
cognac/armagnac
collard greens
colorado
columbus
condiment
condiment/spread
connecticut
cook like a diner
cookbook critic
cookie
cookies
coriander
corn
cornmeal
costa mesa
cottage cheese
couscous
crab
cranberry
cranberry sauce
cream cheese
créme de cacao
crêpe
cr��me de cacao
cuba
cucumber
cumin
cupcake
currant
curry
custard
dairy
dairy free
dallas
date
deep-fry
denver
dessert
digestif
dill
dinner
dip
diwali
dominican republic
dorie greenspan
double boiler
dried fruit
drink
drinks
duck
easter
eau de vie
edible gift
egg
egg nog
eggplant
egypt
emeril lagasse
endive
engagement party
england
entertaining
epi + ushg
epi loves the microwave
escarole
fall
family reunion
fat free
father's day
fennel
feta
fig
fish
flaming hot summer
flat bread
florida
fontina
food processor
fortified wine
fourth of july
france
frangelico
frankenrecipe
freeze/chill
freezer food
friendsgiving
frittata
fritter
frozen dessert
fruit
fruit juice
fry
game
garlic
georgia
germany
gin
ginger
goat cheese
goose
gouda
gourmet
graduation
grains
grand marnier
granola
grape
grapefruit
grappa
green bean
green onion/scallion
grill
grill/barbecue
ground beef
ground lamb
guam
guava
haiti
halibut
halloween
ham
hamburger
hanukkah
harpercollins
hawaii
hazelnut
healdsburg
healthy
herb
high fiber
hollywood
hominy/cornmeal/masa
honey
honeydew
hors d'oeuvre
horseradish
hot drink
hot pepper
house & garden
house cocktail
houston
hummus
ice cream
ice cream machine
iced coffee
iced tea
idaho
illinois
indiana
iowa
ireland
israel
italy
jalapeño
jam or jelly
jamaica
japan
jerusalem artichoke
juicer
jícama
kahlúa
kale
kansas
kansas city
kentucky
kentucky derby
kid-friendly
kidney friendly
kirsch
kitchen olympics
kiwi
kosher
kosher for passover
kumquat
kwanzaa
labor day
lamb
lamb chop
lamb shank
lancaster
las vegas
lasagna
leafy green
leek
legume
lemon
lemon juice
lemongrass
lentil
lettuce
lima bean
lime
lime juice
lingonberry
liqueur
lobster
london
long beach
los angeles
louisiana
louisville
low cal
low carb
low cholesterol
low fat
low sodium
low sugar
low/no sugar
lunar new year
lunch
lychee
macadamia nut
macaroni and cheese
maine
mandoline
mango
maple syrup
mardi gras
margarita
marinade
marinate
marsala
marscarpone
marshmallow
martini
maryland
massachusetts
mayonnaise
meat
meatball
meatloaf
melon
mexico
mezcal
miami
michigan
microwave
midori
milk/cream
minneapolis
minnesota
mint
mississippi
missouri
mixer
molasses
monterey jack
mortar and pestle
mother's day
mozzarella
muffin
mushroom
mussel
mustard
mustard greens
nancy silverton
nebraska
nectarine
new hampshire
new jersey
new mexico
new orleans
new year's day
new year's eve
new york
no meat, no problem
no sugar added
no-cook
non-alcoholic
noodle
north carolina
nut
nutmeg
oat
oatmeal
octopus
ohio
oklahoma
okra
oktoberfest
olive
omelet
one-pot meal
onion
orange
orange juice
oregano
oregon
organic
orzo
oscars
oyster
pacific palisades
paleo
pan-fry
pancake
papaya
paprika
parade
paris
parmesan
parsley
parsnip
party
pasadena
passion fruit
passover
pasta
pasta maker
pastry
pea
peach
peanut
peanut butter
peanut free
pear
pecan
pennsylvania
pepper
pernod
persian new year
persimmon
peru
pescatarian
philippines
phyllo/puff pastry dough
pickles
picnic
pie
pine nut
pineapple
pistachio
pittsburgh
pizza
plantain
plum
poach
poblano
poker/game night
pomegranate
pomegranate juice
poppy
pork
pork chop
pork rib
pork tenderloin
port
portland
pot pie
potato
potato salad
potluck
poultry
poultry sausage
pressure cooker
prosciutto
providence
prune
pumpkin
punch
purim
quail
quiche
quick & easy
quick and healthy
quince
quinoa
rabbit
rack of lamb
radicchio
radish
raisin
ramadan
ramekin
raspberry
raw
red wine
rhode island
rhubarb
rice
ricotta
roast
root vegetable
rosemary
rosh hashanah/yom kippur
rosé
rub
rum
rutabaga
rye
saffron
sage
sake
salad
salad dressing
salmon
salsa
san francisco
sandwich
sandwich theory
sangria
santa monica
sardine
sauce
sausage
sauté
scallop
scotch
seafood
seattle
seed
self
semolina
sesame
sesame oil
shallot
shavuot
shellfish
sherry
shower
shrimp
side
simmer
skewer
slow cooker
smoker
smoothie
snapper
sorbet
soufflé/meringue
soup/stew
sour cream
sourdough
south carolina
soy
soy free
soy sauce
spain
sparkling wine
spice
spinach
spirit
spring
spritzer
squash
squid
st. louis
st. patrick's day
steak
steam
stew
stir-fry
stock
strawberry
stuffing/dressing
sugar conscious
sugar snap pea
sukkot
summer
super bowl
suzanne goin
sweet potato/yam
swiss cheese
switzerland
swordfish
taco
tailgating
tamarind
tangerine
tapioca
tarragon
tart
tea
tennessee
tequila
tested & improved
texas
thanksgiving
thyme
tilapia
tofu
tomatillo
tomato
tortillas
tree nut
tree nut free
triple sec
tropical fruit
trout
tuna
turnip
utah
valentine's day
vanilla
veal
vegan
vegetable
vegetarian
venison
vermont
vermouth
vinegar
virginia
vodka
waffle
walnut
wasabi
washington
washington, d.c.
watercress
watermelon
wedding
weelicious
west virginia
westwood
wheat/gluten-free
whiskey
white wine
whole wheat
wild rice
windsor
wine
winter
wisconsin
wok
yellow squash
yogurt
yonkers
yuca
zucchini
cookbooks
leftovers
snack
snack week
turkey

In [4]:
df.describe()

,rating,calories,protein,fat,sodium,#cakeweek,#wasteless,22-minute meals,3-ingredient recipes,30 days of groceries,...,yellow squash,yogurt,yonkers,yuca,zucchini,cookbooks,leftovers,snack,snack week,turkey
count,20052.000000,1.593500e+04,15890.000000,1.586900e+04,1.593300e+04,20052.000000,20052.000000,20052.000000,20052.000000,20052.000000,...,20052.000000,20052.000000,20052.000000,20052.000000,20052.000000,20052.000000,20052.000000,20052.000000,20052.000000,20052.000000
mean,3.714467,6.322958e+03,100.160793,3.468775e+02,6.225975e+03,0.000299,0.000050,0.000848,0.001346,0.000349,...,0.001247,0.026332,0.000050,0.000299,0.014861,0.000150,0.000349,0.001396,0.000948,0.022741
std,1.340829,3.590460e+05,3840.318527,2.045611e+04,3.333182e+05,0.017296,0.007062,0.029105,0.036671,0.018681,...,0.035288,0.160123,0.007062,0.017296,0.121001,0.012231,0.018681,0.037343,0.030768,0.149080
min,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.750000,1.980000e+02,3.000000,7.000000e+00,8.000000e+01,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.375000,3.310000e+02,8.000000,1.700000e+01,2.940000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,4.375000,5.860000e+02,27.000000,3.300000e+01,7.110000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,5.000000,3.011122e+07,236489.000000,1.722763e+06,2.767511e+07,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
df.count()

title         20052
rating        20052
calories      15935
protein       15890
fat           15869
              ...
cookbooks     20052
leftovers     20052
snack         20052
snack week    20052
turkey        20052
Length: 680, dtype: int64

## Drop the duplicates from the DataFrame

In [6]:
df_without_duplicates = df.drop_duplicates(keep='last')

In [7]:
df_without_duplicates.count()

title         18251
rating        18251
calories      14502
protein       14470
fat           14450
              ...
cookbooks     18251
leftovers     18251
snack         18251
snack week    18251
turkey        18251
Length: 680, dtype: int64

## Check how many values are missing from each column

In [8]:
df_without_duplicates.isnull().sum()

title            0
rating           0
calories      3749
protein       3781
fat           3801
              ...
cookbooks        0
leftovers        0
snack            0
snack week       0
turkey           0
Length: 680, dtype: int64

## Delete columns which contains only with value NA

In [9]:
new_df = df_without_duplicates.dropna(axis=1, how='all')

In [10]:
new_df.count()

title         18251
rating        18251
calories      14502
protein       14470
fat           14450
              ...
cookbooks     18251
leftovers     18251
snack         18251
snack week    18251
turkey        18251
Length: 680, dtype: int64

In [11]:
new_df.head()

,title,rating,calories,protein,fat,sodium,#cakeweek,#wasteless,22-minute meals,3-ingredient recipes,...,yellow squash,yogurt,yonkers,yuca,zucchini,cookbooks,leftovers,snack,snack week,turkey
0,"Lentil, Apple, and Turkey Wrap",2.500,426.0,30.0,7.0,559.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Boudin Blanc Terrine with Red Onion Confit,4.375,403.0,18.0,23.0,1439.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Potato and Fennel Soup Hodge,3.750,165.0,6.0,7.0,165.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Mahi-Mahi in Tomato Olive Sauce,5.000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Spinach Noodle Casserole,3.125,547.0,20.0,32.0,452.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
new_df.loc[new_df.title == 'Strawberry-Soy Milk Shake ']

,title,rating,calories,protein,fat,sodium,#cakeweek,#wasteless,22-minute meals,3-ingredient recipes,...,yellow squash,yogurt,yonkers,yuca,zucchini,cookbooks,leftovers,snack,snack week,turkey
2979,Strawberry-Soy Milk Shake,3.75,170.0,12.0,6.0,34.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
new_df[['title', 'honey']].loc[new_df.title == 'Strawberry-Soy Milk Shake ']

                           title  honey
2979  Strawberry-Soy Milk Shake     1.0

In [14]:
def get_title(list_of_ingredients, df):
	for i in list_of_ingredients:
		if not i in df.columns.to_list():
			print('Wrong ingridient(s)')
			return
	condition = 1
	for ingredient in list_of_ingredients:
		condition &= (new_df[ingredient] == 1)
	dishes = new_df[condition].sort_values(['rating'], ascending = False)[['title', 'rating']]
	dishes = dishes.iloc[:3]
	return dishes

In [15]:
get_title(['apple', 'turkey'], new_df)

                                                  title  rating
7438      Cider-Basted Turkey with Roasted Apple Gravy    5.000
7017  Roast Heritage Turkey with Bacon-Herb and Cide...   4.375
8414  Roast Turkey with Apples, Onions, Fried Sage L...   4.375

In [16]:
list_of_ingredients = ['apple', 'turkey']
condition = 1
for ingredient in list_of_ingredients:
    condition &= (new_df[ingredient] == 1)
dishes = new_df[condition].sort_values(['rating'], ascending = False)['title']
dishes = dishes.iloc[:3]
dishes = [dish.strip().replace(' ', '-') for dish in dishes]
dishes

['Cider-Basted-Turkey-with-Roasted-Apple-Gravy',
 'Roast-Heritage-Turkey-with-Bacon-Herb-and-Cider-Gravy',
 'Roast-Turkey-with-Apples,-Onions,-Fried-Sage-Leaves,-and-Apple-Cider-Gravy']

In [17]:
def get_url(dishes):
	sep_dishes = dishes
	sep_dishes.strip().replace(' ', '-')
	search_url = f'https://www.epicurious.com/search/{sep_dishes}'
	search_resp = requests.get(search_url, headers={'User-Agent': 'Custom'})
	bs = BeautifulSoup(search_resp.text, 'html.parser')
	urls = bs.find_all('a', href=True)
	refs = bs.find()
	for url in urls:
		if url.get_text() == dishes:
			return 'https://www.epicurious.com' + url.get('href')

In [18]:
print(get_url('Cider-Basted Turkey with Roasted Apple Gravy'))

https://www.epicurious.com/recipes/food/views/cider-basted-turkey-with-roasted-apple-gravy-104498

In [19]:
import requests
from bs4 import BeautifulSoup

search_url = f'https://www.epicurious.com/search/{dishes[0]}'
search_resp = requests.get(search_url, headers={'User-Agent': 'Custom'})
bs = BeautifulSoup(search_resp.text, 'html.parser')
urls = bs.find_all('a', href=True)
refs = bs.find()
print(urls[1])
print(urls[1].get('href'))
print(urls[1].get_text())

<a data-reactid="72" href="/recipes/food/views/cider-basted-turkey-with-roasted-apple-gravy-104498">Cider-Basted Turkey with Roasted Apple Gravy</a>
/recipes/food/views/cider-basted-turkey-with-roasted-apple-gravy-104498
Cider-Basted Turkey with Roasted Apple Gravy

In [20]:
def recommendation(list_of_ingredients, df):
    print("III. TOP-3 SIMILAR RECIPES:")
    title_rating = get_title(list_of_ingredients, df)
    #print(title_rating)
    for i, row in title_rating.iterrows():
        dish = row.title.strip()
        rating = row.rating
        url = get_url(dish)
        print(f'{dish}, rating: {rating}, URL: {url}')

In [21]:
list_of_ingredients = ['apple', 'turkey']
recommendation(list_of_ingredients, new_df)

III. TOP-3 SIMILAR RECIPES:
Cider-Basted Turkey with Roasted Apple Gravy, rating: 5.0, URL: https://www.epicurious.com/recipes/food/views/cider-basted-turkey-with-roasted-apple-gravy-104498
Roast Heritage Turkey with Bacon-Herb and Cider Gravy, rating: 4.375, URL: https://www.epicurious.com/recipes/food/views/roast-heritage-turkey-with-bacon-herb-and-cider-gravy-350421
Roast Turkey with Apples, Onions, Fried Sage Leaves, and Apple Cider Gravy, rating: 4.375, URL: https://www.epicurious.com/recipes/food/views/roast-turkey-with-apples-onions-fried-sage-leaves-and-apple-cider-gravy-104276